baseurl = "https://shishuai.org/"
languageCode = "en-us"
title = "shishuai`s blog"
theme = "hugo-my-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 3
# [[menu.main]]
#     name = "Notes"
#     url = "/note/"
#     weight = 4
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 5
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 6
# [[menu.main]]
#     name = "Subscribe"
#     url = "/index.xml"

[params]
    description = "A website built through Hugo."
    footer = "&copy; [Shuai Shi](https://shishuai.org) 2020 -- 2020 | [Github](https://github.com/markshih91)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true