baseurl = "https://shishuai.org/"
languageCode = "en-us"
title = "shishuai`s blog"
theme = "hugo-my-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 3
# [[menu.main]]
#     name = "Notes"
#     url = "/note/"
#     weight = 4
[[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 5
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 6
# [[menu.main]]
#     name = "Subscribe"
#     url = "/index.xml"

[params]
    description = "A website built through Hugo."
    footer = "&copy; [shuai Shi](https://shishuai.org) 2020 -- 2020 | [Github](https://github.com/markshih91)"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# [Params]
#   enableGitalk = true
[Params.Gitalk]
    clientID = "f6bc62a424470aaf4f8a" # Your client ID
    clientSecret = "4a3fa58e1f74f9480f6a5602c1320ce42a660d49" # Your client secret
    repo = "markshih91.github.io" # The repo to store comments
    owner = "markshih91" # Your GitHub ID
    admin= "markshih91" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    # id= "location.pathname" # The unique id of the page.
    labels= "gitalk" # Github issue labels. If you used to use Gitment, you can change it
    perPage= 100 # Pagination size, with maximum 100.
    pagerDirection= "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually= false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode= false # Enable hot key (cmd|ctrl + enter) submit comment.